site_name: 'Enclave Documentation'
site_description: 'Deploy, manage and scale your Enclave networks'

theme:
  name: 'material'

  features:
    - navigation.sections
    - navigation.tabs
    #- search.suggest       # insiders only
    #- search.highlight     # insiders only
    #- navigation.tracking
    #- navigation.expand
    #- navigation.indexes
    #- navigation.top
    #- toc.integrate

  static_templates:
    - 404.html

  # necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/favicon.ico
  favicon: assets/favicon.ico
  icon:
    logo: logo
#  palette:
#    primary: red

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/enclave-networks
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/enclavenetworks/enclave
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/enclavenetworks
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/enclave-networks/
#  enable documentation versioning support 
#  version:
#    provider: mike

google_analytics:
  - UA-244950-15
  - auto

markdown_extensions:
#  - pymdownx.highlight:
#      linenums: true
#      linenums_style: pymdownx.inline
  - pymdownx.tabbed
  - pymdownx.superfences
  - footnotes
  - toc

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search:
      lang: en
  - redirects:
      redirect_maps:
        quick-start.md: getting-started/installation.md
        keywords/full-mesh.md: management/policy.md
        keywords/dns-load-balancing.md: networking/dns.md

nav:
  - Home: 
    - Enclave documentation: index.md
#    - Community: community.md
#    - Glossary: glossary.md

    - Setup:
      - Getting started guide:
        - 1. Installation: getting-started/installation.md
        - 2. Attach tags: getting-started/attach-tags.md
        - 3. Define policy: getting-started/define-policy.md
        - 4. Next steps: getting-started/next-steps.md

      - Install guides:
        - Windows: install/windows.md
        - Linux:
          - Ubuntu / Debian: install/ubuntu.md
#          - CentOS / RHEL: install/rhel.md
#          - Fedora: install/fedora.md
#          - Amazon Linux: install/amazon-linux.md
#          - Arch Linux: install/arch.md
#          - Raspbian: install/raspbian.md
#        - Containers:
#          - Docker: install/docker.md
#          - Kubernetes: install/kubernetes.md
#        - Network Attached Storage:
#          - Synology NAS: install/synology-nas.md
#      - Running enclave: install/running-enclave.md
      - Windows: setup/windows.md

#    - Concepts:
#      - Principles: concepts/principles.md
#      - Architecture: concepts/architecture.md
#      - Connectivity:
#        - Requirements: concepts/connectivity/requirements.md
#        - NAT traversal: concepts/connectivity/nat.md
#        - Agent telemetry: concepts/connectivity/telemetry.md
#      - Security:
#        - Threat model: concepts/security/threat-model.md
#        - Security considerations: concepts/security/considerations.md
#        - Certificates: concepts/security/certificates.md
#        - Encryption: concepts/security/encryption.md

    - Management:
#      - Organisations: management/organisations.md
#      - Endpoint management: management/endpoint-management.md
#      - Enrolment keys: management/enrolment.md
      - Policy: management/policy.md
      - Tags: management/tags.md
#      - Profiles: management/profiles.md
#      - Examples: management/examples.md

#    - Networking:
#      - Topologies: networking/topologies.md
#      - IP addresses: networking/ip-addresses.md
#      - DNS: networking/dns.md
#      - ARP: networking/arp.md
#      - Multicast: networking/multicast.md

#    - Fabric commands (CLI):
#      - All:
#        - status: cli/status.md
#        - enrol: cli/enrol.md
#        - start: cli/start.md
#        - stop: cli/stop.md
#        - add: cli/add.md
#        - remove: cli/remove.md
#        - enable: cli/enable.md
#        - disable: cli/disable.md
#        - help: cli/help.md
#        - version: cli/version.md
#      - Windows only:
#        - list-adapters: cli/list-adapters.md
#        - install-adapter: cli/install-adapter.md
#        - remove-adapter: cli/remove-adapter.md

  - REST API:
      Overview: api/index.md
      Reference: api/reference.md
#      Guides: api/guides.md

  - Tutorials: tutorials/index.md

  - Knowledge Base: kb/index.md
  
  - Troubleshooting: troubleshooting/index.md

  #- Support:
  #  - Contact us: support/contact.md
  #  - Billing:
  #    - Frequently asked questions: support/billing.md
  #  - Account:
  #    - Ownership, transfer and closure: support/account.md
